project_id = "wywlevstbiivkmcmmmei"

[functions.process-email]
verify_jwt = false

[functions.gmail-auth-init]
verify_jwt = false

[functions.gmail-auth-callback]
verify_jwt = false

[functions.outlook-auth-init]
verify_jwt = false

[functions.outlook-auth-callback]
verify_jwt = false
