import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
const faqs = [
  { q: "Where does Dutaly get its answers?", a: "Support answers are grounded in the knowledge base you provide: FAQs, policies, snippets, and uploaded documents. Your instructions control tone and behavior. If the information isn't there, Dutaly drafts for review or escalates instead of inventing an answer." },
  { q: "Can I review replies before they are sent?", a: "Yes. Use approval-only mode to review drafts, or enable automatic replies with confidence thresholds. You can set different thresholds by category and pause automation whenever you need to." },
  { q: "Which inboxes can I connect?", a: "Connect Gmail and Google Workspace using Google sign-in, or a supported IMAP/SMTP inbox such as Zoho, Fastmail, or your hosted email domain. Outlook is not currently supported." },
  { q: "What happens when a customer is upset?", a: "Dutaly checks sentiment and flags angry or high-risk conversations for human attention. Automatic replies are paused for these conversations so you can take over with the full context." },
  { q: "Can I use my own email templates?", a: "Yes. Create branded templates with fonts, colors, formatting, and a footer, or make one with AI. In Inbox Intelligence, select a saved template from the slash menu and review the message before sending." },
  { q: "How do the plans work?", a: "Starter, Growth, and Scale plans have different email limits, connected-account limits, and automation features. A 14-day trial lets you get started. Visit the pricing page for current plan details." },
];
export function FaqSection() {
  return <section id="faq" className="landing-band" aria-labelledby="landing-faq-heading"><div className="landing-wrap grid gap-12 lg:grid-cols-[1fr_1.5fr]"><div><p className="landing-label mb-8"><span>05</span> Good questions</p><h2 id="landing-faq-heading" className="landing-title">Before you<br />hand it over.</h2><p className="mt-5 max-w-[320px] text-base leading-[1.8] text-landing-muted">A few things worth knowing about your new email agent.</p></div><Accordion type="single" collapsible>{faqs.map((faq, index) => <AccordionItem key={faq.q} value={`faq-${index}`} className="border-landing-line"><AccordionTrigger className="landing-ui py-6 text-left text-base font-normal text-landing-foreground hover:no-underline">{faq.q}</AccordionTrigger><AccordionContent className="pb-6 pr-6 text-[15px] leading-[1.8] text-landing-muted">{faq.a}</AccordionContent></AccordionItem>)}</Accordion></div></section>;
}
